# Generated by Django 4.2 on 2023-04-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_rename_badges_author_num_followers_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
